In [28]:
#Importing some modules here, but rest will be imported as per the requirement
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline 
import scipy.stats as stats
import warnings
warnings.simplefilter('ignore')

In [126]:
data=pd.read_csv("Train_Dataset.csv",low_memory=False)

In [127]:
Categorical_columns=["Car_Owned",
                     "Bike_Owned",
                     "Active_Loan",
                     "House_Own",
                     "Accompany_Client",
                     "Client_Income_Type",
                     "Client_Education",
                     "Client_Marital_Status",
                     "Client_Gender",
                     "Loan_Contract_Type",
                     "Client_Housing_Type",
                     "Mobile_Tag",
                     "Homephone_Tag",
                     "Workphone_Working",
                     "Client_Occupation",
                     "Cleint_City_Rating",
                     "Application_Process_Day",
                     "Client_Permanent_Match_Tag",
                     "Client_Contact_Work_Tag",
                     "Type_Organization",
                     "Default"]
####################################################################3
Numerical_columns=[]
for each in data.columns:
    #print(each)
    if each in Categorical_columns:
        #print(each)
        pass
    else:
        Numerical_columns.append(each)
######################################################################
Categorical_columns.remove("Default")        
Numerical_columns.remove("ID")

In [190]:
data1_final=pd.read_csv("pre-processing done except outliers.csv")

data1_final.drop(["Unnamed: 0"],axis=1,inplace=True)

#data1_final.drop(Numerical_columns,axis=1,inplace=True)

In [191]:
data1_final

,Client_Income,Car_Owned,Bike_Owned,Active_Loan,House_Own,Child_Count,Credit_Amount,Loan_Annuity,Accompany_Client,Client_Income_Type,...,Client_Permanent_Match_Tag,Client_Contact_Work_Tag,Type_Organization,Score_Source_1,Score_Source_2,Score_Source_3,Social_Circle_Default,Phone_Change,Credit_Bureau,Default
0,6750.0,0.0,0.0,1.0,0.0,0.0,61190.55,3416.85,Alone,Commercial,...,Yes,Yes,Self-employed,0.568066,0.478787,0.521139,0.018600,63.000000,1.880278,0
1,20250.0,1.0,0.0,1.0,1.0,0.0,15282.00,1826.55,Alone,Service,...,Yes,Yes,Government,0.563360,0.215068,0.521139,0.118391,975.486597,1.880278,0
2,18000.0,0.0,0.0,1.0,0.0,1.0,59527.35,2788.20,Alone,Service,...,Yes,Yes,Self-employed,0.509964,0.552795,0.329655,0.074200,277.000000,0.000000,0
3,15750.0,0.0,0.0,1.0,1.0,0.0,53870.40,2295.45,Alone,Retired,...,Yes,Yes,XNA,0.509964,0.135182,0.631355,0.118391,1700.000000,3.000000,0
4,33750.0,1.0,0.0,1.0,0.0,2.0,133988.40,3547.35,Alone,Commercial,...,Yes,Yes,Business Entity Type 3,0.508199,0.301182,0.355639,0.202100,674.000000,1.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121851,29250.0,0.0,0.0,0.0,1.0,0.0,107820.00,3165.30,Relative,Service,...,Yes,No,Business Entity Type 2,0.391354,0.173527,0.184116,0.057700,0.000000,1.000000,1
121852,15750.0,0.0,1.0,1.0,0.0,0.0,104256.00,3388.05,Alone,Commercial,...,Yes,Yes,Self-employed,0.509964,0.371559,0.406617,0.082500,4.000000,0.000000,0
121853,8100.0,0.0,1.0,0.0,1.0,1.0,55107.90,2989.35,Alone,Govt Job,...,No,No,Trade: type 6,0.169049,0.048079,0.521139,0.118391,0.000000,1.880278,0
121854,38250.0,1.0,1.0,0.0,1.0,0.0,45000.00,2719.35,Alone,Service,...,Yes,Yes,Business Entity Type 3,0.182737,0.103538,0.077499,0.097900,0.000000,2.000000,0
121855,9000.0,1.0,1.0,1.0,1.0,1.0,62428.95,4201.65,Alone,Commercial,...,Yes,Yes,Business Entity Type 3,0.509964,0.556414,0.298595,0.103100,805.000000,0.000000,0

In [192]:
###########################################################
############################################################
#Function that will list out column by column outliers' Index values. We will check patterns for those.
def outlier_identification(df,Numerical_columns):
    dataframe=df
    dataframe_desc=dataframe.describe()
    for col in Numerical_columns:
        Quartile3=list(dataframe[col][dataframe[col]>dataframe_desc[col]["75%"]].index)
        Quartile1=list(dataframe[col][dataframe[col]<dataframe_desc[col]["25%"]].index)
        try:
            dataframe.replace(dataframe[col][Quartile3],dataframe_desc[col]["75%"],axis=0,inplace=True)
        except:
            pass
        try :
            dataframe.replace(dataframe[col][Quartile1],dataframe_desc[col]["75%"],axis=0,inplace=True)
        except:
            pass
        #outliers_values.update({col:[Quartile1,Quartile3]})
    return
###########################################################
############################################################

In [193]:
outlier_identification(data1_final,Numerical_columns)

In [194]:
data1_final

,Client_Income,Car_Owned,Bike_Owned,Active_Loan,House_Own,Child_Count,Credit_Amount,Loan_Annuity,Accompany_Client,Client_Income_Type,...,Client_Permanent_Match_Tag,Client_Contact_Work_Tag,Type_Organization,Score_Source_1,Score_Source_2,Score_Source_3,Social_Circle_Default,Phone_Change,Credit_Bureau,Default
0,6750.0,0.0,0.0,1.0,0.0,0.0,61190.55,3416.85,Alone,Commercial,...,Yes,Yes,Self-employed,0.568066,0.478787,0.521139,0.018600,63.000000,1.880278,0
1,20250.0,1.0,0.0,1.0,1.0,0.0,15282.00,1826.55,Alone,Service,...,Yes,Yes,Government,0.563360,0.215068,0.521139,0.118391,975.486597,1.880278,0
2,18000.0,0.0,0.0,1.0,0.0,1.0,59527.35,2788.20,Alone,Service,...,Yes,Yes,Self-employed,0.509964,0.552795,0.329655,0.074200,277.000000,0.000000,0
3,15750.0,0.0,0.0,1.0,1.0,0.0,53870.40,2295.45,Alone,Retired,...,Yes,Yes,XNA,0.509964,0.135182,0.631355,0.118391,1700.000000,3.000000,0
4,33750.0,1.0,0.0,1.0,0.0,2.0,133988.40,3547.35,Alone,Commercial,...,Yes,Yes,Business Entity Type 3,0.508199,0.301182,0.355639,0.202100,674.000000,1.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121851,29250.0,0.0,0.0,0.0,1.0,0.0,107820.00,3165.30,Relative,Service,...,Yes,No,Business Entity Type 2,0.391354,0.173527,0.184116,0.057700,0.000000,1.000000,1
121852,15750.0,0.0,1.0,1.0,0.0,0.0,104256.00,3388.05,Alone,Commercial,...,Yes,Yes,Self-employed,0.509964,0.371559,0.406617,0.082500,4.000000,0.000000,0
121853,8100.0,0.0,1.0,0.0,1.0,1.0,55107.90,2989.35,Alone,Govt Job,...,No,No,Trade: type 6,0.169049,0.048079,0.521139,0.118391,0.000000,1.880278,0
121854,38250.0,1.0,1.0,0.0,1.0,0.0,45000.00,2719.35,Alone,Service,...,Yes,Yes,Business Entity Type 3,0.182737,0.103538,0.077499,0.097900,0.000000,2.000000,0
121855,9000.0,1.0,1.0,1.0,1.0,1.0,62428.95,4201.65,Alone,Commercial,...,Yes,Yes,Business Entity Type 3,0.509964,0.556414,0.298595,0.103100,805.000000,0.000000,0

In [196]:
global random_state #this will be set for repeatability and will not be disturbed.
random_state=1
#This will be completely fixed and referenced everywhere
########################################################################
x=data1_final.drop("Default",axis=1) # The rest four columns create our independent columns
y=data1_final["Default"].astype("int")
##########################################################################
from scipy.stats import zscore
######################################
x[Numerical_columns]=x[Numerical_columns].apply(zscore)
################################################################################
#data1_final[Numerical_columns]=data1_final[Numerical_columns].astype("float16")

In [197]:
from sklearn.preprocessing import OrdinalEncoder
ord_enc = OrdinalEncoder()
x[Categorical_columns] = ord_enc.fit_transform(x[Categorical_columns])

In [198]:
x

,Client_Income,Car_Owned,Bike_Owned,Active_Loan,House_Own,Child_Count,Credit_Amount,Loan_Annuity,Accompany_Client,Client_Income_Type,...,Application_Process_Hour,Client_Permanent_Match_Tag,Client_Contact_Work_Tag,Type_Organization,Score_Source_1,Score_Source_2,Score_Source_3,Social_Circle_Default,Phone_Change,Credit_Bureau
0,-0.890006,0.0,0.0,1.0,0.0,-0.581994,0.028767,0.485680,1.0,1.0,...,1.527981,1.0,1.0,42.0,0.478182,-0.055143,0.059418,-1.302218,-1.102515,-0.006558
1,0.297809,1.0,0.0,1.0,1.0,-0.581994,-1.126330,-0.624685,1.0,5.0,...,-0.638514,1.0,1.0,11.0,0.444934,-0.420003,0.059418,0.014762,0.016453,-0.006558
2,0.099840,0.0,0.0,1.0,0.0,0.811070,-0.013080,0.046749,1.0,5.0,...,0.007107,1.0,1.0,42.0,0.067700,0.047249,-1.051530,-0.568447,-0.840090,-1.103246
3,-0.098129,0.0,0.0,1.0,1.0,-0.581994,-0.155414,-0.297294,1.0,4.0,...,0.908983,1.0,1.0,57.0,0.067700,-0.530528,0.698862,0.014762,0.904913,0.646529
4,1.485623,1.0,0.0,1.0,0.0,2.204134,1.860421,0.576796,1.0,1.0,...,0.007107,1.0,1.0,5.0,0.055226,-0.300863,-0.900779,1.119491,-0.353255,-0.519988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121851,1.089685,0.0,0.0,0.0,1.0,-0.581994,1.202003,0.310045,6.0,5.0,...,1.218482,1.0,0.0,4.0,-0.770258,-0.477477,-1.895914,-0.786203,-1.179771,-0.519988
121852,-0.098129,0.0,1.0,1.0,0.0,-0.581994,1.112329,0.465571,1.0,1.0,...,-0.019515,1.0,1.0,42.0,0.067700,-0.203496,-0.605012,-0.458909,-1.174866,-1.103246
121853,-0.771224,0.0,1.0,0.0,1.0,0.811070,-0.124277,0.187195,1.0,2.0,...,-0.329015,0.0,0.0,50.0,-2.340812,-0.651037,0.059418,0.014762,-1.179771,-0.006558
121854,1.881561,1.0,1.0,0.0,1.0,-0.581994,-0.378601,-0.001322,1.0,5.0,...,-0.019515,1.0,1.0,5.0,-2.244110,-0.574308,-2.514486,-0.255670,-1.179771,0.063270
121855,-0.692037,1.0,1.0,1.0,1.0,0.811070,0.059926,1.033636,1.0,1.0,...,-1.876511,1.0,1.0,5.0,0.067700,0.052256,-1.231734,-0.187044,-0.192612,-1.103246

In [204]:
from sklearn.model_selection import train_test_split
#######################################################################
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=random_state)
#######################################################################

In [205]:
#Random Over sampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler()

In [206]:
from imblearn.over_sampling import RandomOverSampler
ros2 = RandomOverSampler()
from imblearn.under_sampling import RandomUnderSampler
rus2 = RandomUnderSampler()

In [207]:
from imblearn.over_sampling import RandomOverSampler
ros3 = RandomOverSampler()
from imblearn.under_sampling import RandomUnderSampler
rus3 = RandomUnderSampler()

In [208]:
X_train,y_train=ros.fit_resample(X_train,y_train)
X_train,y_train=rus.fit_resample(X_train,y_train)

In [209]:
X_train,y_train=ros2.fit_resample(X_train,y_train)
X_train,y_train=rus2.fit_resample(X_train,y_train)

In [210]:
X_train,y_train=ros3.fit_resample(X_train,y_train)
X_train,y_train=rus3.fit_resample(X_train,y_train)

In [211]:
X_train.shape

(156896, 38)

In [212]:
pd.Series(y_train).value_counts()

0    78448
1    78448
Name: Default, dtype: int64

In [213]:
#############################################################################

In [214]:
Models_list={}
#######################################################################
# No Parameters are given here for the models because we want to make it
#to the cross validation. We have included most of the supervised learning 
# method unitialized so that we can go for the treatment later on.
#
#######################################################################
#
#Logistic Regression Model and its Tuning.
#######################################################################
from sklearn.linear_model import LogisticRegression
#######################################################################
LR_model = LogisticRegression()
Models_list.update({"LogisticRegression":LR_model})
#######################################################################
######################################################################
#
#Gaussian Naive Bayes Model
#######################################################################
from sklearn.naive_bayes import GaussianNB
######################################################################
NB_model = GaussianNB()
Models_list.update({"NaiveBayes":NB_model})
#######################################################################
#######################################################################
#
#KNN Model
#######################################################################
from sklearn.neighbors import KNeighborsClassifier
#########################################################
KNN = KNeighborsClassifier()
Models_list.update({"KNN":KNN})
#######################################################################
#######################################################################
#
# Support Vector Classifier
######################################################################
from sklearn.svm import SVC
#######################################################################
support_vector = SVC(probability = True)
Models_list.update({"support_vector":support_vector})
#######################################################################
#######################################################################
#
#Decicion Tree Model
########################################################################
from sklearn.tree import DecisionTreeClassifier
#######################################################################
decision_tree=DecisionTreeClassifier()
Models_list.update({"decision_tree":decision_tree})
#######################################################################
#######################################################################
#
#Bagging Classifier
######################################################################
from sklearn.ensemble import BaggingClassifier
######################################################################
bagging=BaggingClassifier(random_state=random_state)
Models_list.update({"bagging":bagging})
#######################################################################
#######################################################################
#
#Adaboost Classifier
######################################################################
from sklearn.ensemble import AdaBoostClassifier
#####################################################################
adaboost=AdaBoostClassifier(n_estimators=10,random_state=random_state)
Models_list.update({"adaboost":adaboost})
#######################################################################
#######################################################################
#
#Gradient Boosting Classifier
########################################################################
from sklearn.ensemble import GradientBoostingClassifier
########################################################################
gradientboost = GradientBoostingClassifier(random_state=random_state)
Models_list.update({"gradientboost":gradientboost})
#######################################################################
#######################################################################
#
#Random Forest Classifier
#######################################################################
from sklearn.ensemble import RandomForestClassifier
#######################################################################
random_forest = RandomForestClassifier(random_state=random_state)
Models_list.update({"random_forest":random_forest})
#######################################################################
#######################################################################
##MPLC Classifier
#######################################################################
#from sklearn.neural_network import MLPClassifier
#######################################################################
#Mlpc = MLPClassifier()
#Models_list.update({"MLPC":Mlpc})
######################################################################
Models_chosen=[]
############################################################
for key in Models_list:
    Models_chosen.append(Models_list[key])
##################################################

In [215]:
from mlxtend.classifier import StackingCVClassifier

sclf = StackingCVClassifier(classifiers = Models_chosen[0:3],
                                shuffle = False,
                                use_probas = True,
                                cv = 5,
                                meta_classifier = SVC(probability = True),
                                n_jobs = -1)
Model=sclf

In [216]:
X_train.shape

(156896, 38)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score as area_under_curve
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import confusion_matrix
Model.fit(X_train,y_train)
Model_prediction=Model.predict(X_test)
train_score=Model.score(X_train,y_train)
test_score=Model.score(X_test,y_test)
Accuracy=accuracy_score(y_test,Model_prediction)
Recall=recall_score(y_test,Model_prediction)
area=area_under_curve(y_test,Model_prediction)
#probability=Model.predict_proba(X_test)
confusion_df=confusion_matrix(y_test, Model_prediction, labels=[0, 1])
#False_p_rate,True_p_rate,thresh=roc_curve(np.array(y_test.ravel()),probability[:,1])
report=classification_report(y_test, Model_prediction, labels=[0, 1])

In [ ]:
pd.DataFrame(confusion_df)

In [ ]:
train_score

In [ ]:
test_score

In [ ]:
Accuracy

In [ ]:
Recall

In [ ]:
#1
data3=pd.read_csv("pre-processing done test_data.csv")

data5=data3["ID"]
data3.drop(["Unnamed: 0","ID"],axis=1,inplace=True)

In [ ]:
outlier_identification(data1_final,Numerical_columns)

In [ ]:
data3[Categorical_columns]=data3[Categorical_columns].astype("category")

In [ ]:
#2
#new_predict=Model.predict(data3.drop(Numerical_columns,axis=1))
new_predict=Model.predict(data3)
pd.Series(new_predict).value_counts()

In [188]:
#3
data4=data3.copy()

data4["Default"]=new_predict

data4["ID"]=data5

In [189]:
#4
data4.set_index("ID")

data4=data4[["ID","Default"]]

data4.to_csv("hackathon_prediction_4.csv")